-- A small fixed historical universe — picked here, not derived from the
-- *current* S&P 500, so the backtester doesn't bake in survivorship bias.
-- Add delisted tickers (e.g. LEH, GE pre-spin) when extending the universe.
INSERT INTO symbols (symbol, name, sector, listed_at) VALUES
    ('AAPL', 'Apple Inc.',                    'Technology',          '1980-12-12'),
    ('MSFT', 'Microsoft Corporation',         'Technology',          '1986-03-13'),
    ('GOOGL','Alphabet Inc. Class A',         'Communication Services','2004-08-19'),
    ('AMZN', 'Amazon.com Inc.',               'Consumer Discretionary','1997-05-15'),
    ('META', 'Meta Platforms Inc.',           'Communication Services','2012-05-18'),
    ('NVDA', 'NVIDIA Corporation',            'Technology',          '1999-01-22'),
    ('JPM',  'JPMorgan Chase & Co.',          'Financials',          '1969-03-05'),
    ('BAC',  'Bank of America Corp.',         'Financials',          '1986-01-02'),
    ('WFC',  'Wells Fargo & Company',         'Financials',          '1972-01-03'),
    ('GS',   'Goldman Sachs Group Inc.',      'Financials',          '1999-05-04'),
    ('JNJ',  'Johnson & Johnson',             'Healthcare',          '1944-09-25'),
    ('PFE',  'Pfizer Inc.',                   'Healthcare',          '1942-06-22'),
    ('UNH',  'UnitedHealth Group Inc.',       'Healthcare',          '1984-10-17'),
    ('ABBV', 'AbbVie Inc.',                   'Healthcare',          '2013-01-02'),
    ('MRK',  'Merck & Co. Inc.',              'Healthcare',          '1978-01-03'),
    ('XOM',  'Exxon Mobil Corporation',       'Energy',              '1972-01-03'),
    ('CVX',  'Chevron Corporation',           'Energy',              '1972-01-03'),
    ('COP',  'ConocoPhillips',                'Energy',              '1972-01-03'),
    ('PG',   'Procter & Gamble Co.',          'Consumer Staples',    '1929-01-02'),
    ('KO',   'The Coca-Cola Company',         'Consumer Staples',    '1962-01-02'),
    ('PEP',  'PepsiCo Inc.',                  'Consumer Staples',    '1972-06-01'),
    ('WMT',  'Walmart Inc.',                  'Consumer Staples',    '1972-08-25'),
    ('COST', 'Costco Wholesale Corporation',  'Consumer Staples',    '1985-12-05'),
    ('HD',   'The Home Depot Inc.',           'Consumer Discretionary','1981-09-22'),
    ('NKE',  'NIKE Inc.',                     'Consumer Discretionary','1980-12-02'),
    ('MCD',  'McDonalds Corporation',         'Consumer Discretionary','1965-04-21'),
    ('DIS',  'The Walt Disney Company',       'Communication Services','1957-11-12'),
    ('V',    'Visa Inc.',                     'Financials',          '2008-03-19'),
    ('MA',   'Mastercard Incorporated',       'Financials',          '2006-05-25'),
    ('SPY',  'SPDR S&P 500 ETF Trust',        'Index ETF',           '1993-01-22');
